# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lionsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badtrait',
            old_name='super_for',
            new_name='sober_for',
        ),
    ]
