# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lionsapp', '0002_auto_20170616_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='habbit',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habbit',
            name='last_done',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
