# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lionsapp', '0003_auto_20170616_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='habbit',
            name='image',
            field=models.ImageField(default='images/placeholder.png', upload_to='images'),
        ),
    ]
