# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lionsapp', '0004_habbit_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habbit',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='habbit',
            name='last_done',
        ),
        migrations.AddField(
            model_name='habbit',
            name='description',
            field=models.CharField(default=0, max_length=8000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habbit',
            name='image',
            field=models.ImageField(default='images/good_habbit.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='habbitcheckin',
            name='check_in_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
