# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lionsapp', '0005_auto_20170619_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='habbit',
            name='good_for',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habbit',
            name='super_for',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
