# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lionsapp', '0006_auto_20170620_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habbit',
            name='good_for',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habbit',
            name='super_for',
            field=models.IntegerField(default=0),
        ),
    ]
